### ISSUE TITLE
ERROR - Failed during configuration: Have not found any log file for pma-filter jail

### ISSUE THREAD

**Issue by ghost** [bunkerity/bunkerized-phpmyadmin#2]
Hi @bunkerity ,

Hope you are all well !

I tried in a docker-compose with traefik as reverse proxy to setup "**bunkerized-phpmyadmin**" but I have an error while starting the container.

<img width="1150" alt="Screenshot 2020-12-09 at 08 18 54" src="https://user-images.githubusercontent.com/1963546/101597781-75bda400-39f7-11eb-8687-e917ae0e7445.png">

Here is an excerpt of my docker-compose:
```yaml
  phpmyadmin:
    image: lucmichalski/bunkerized-phpmyadmin:latest
    container_name: phpmyadmin
    build:
      context: .docker/bunkerized-phpmyadmin
      dockerfile: Dockerfile    
      args:
      - PMA_VERSION=5.0.4
    expose:
    - 80
    - 443
    hostname: phpmyadmin
    labels:
    - "org.label-schema.group=admin"
    - "traefik.enable=true"
    - "traefik.docker.network=web"
    - "traefik.http.routers.phpmyadmin.rule=Host(`xxxx-xxxx.xxx-network.com`) && PathPrefix(`/devops/pma`)"
    - 'traefik.http.routers.phpmyadmin.tls=true'
    - 'traefik.http.routers.phpmyadmin.tls.certresolver=letsencrypt'
    - "traefik.http.routers.phpmyadmin.service=phpmyadmin@docker"
    - "traefik.http.routers.phpmyadmin.entrypoints=https"
    - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"  
    - "traefik.http.middlewares.phpmyadmin.compress=true"
    environment:
    - AUTO_LETS_ENCRYPT=no 
    - REDIRECT_HTTP_TO_HTTPS=no
    - SERVER_NAME=xxxx-xxxx.xxx-network.com
    - PMA_ABSOLUTE_URI=/devops/pma
    - SERVERS_1_host=mariadb
    - SERVERS_1_port=3306
    - SERVERS_1_AllowRoot=false
    - SERVERS_1_user=${MYSQL_USER}
    - SERVERS_1_password=${MYSQL_PASSWORD}
    networks:
    - internal
    - web
    depends_on:
    - mariadb
    volumes:
    - pma-logs:/var/log
```

What can I do to fix it ? Thanks for any insights or inputs on that issue mate :-)

Cheers,
Luc Michalski
